package zeus.zeuscompiler.rain.compiler.syntaxtree.shapes;

public enum ShapeProperty {
  HEIGHT,
  WIDTH,
  BACKGROUND_COLOR_ENABLED,
  BACKGROUND_COLOR,
  BORDER_ENABLED,
  BORDER_COLOR,
  BORDER_WIDTH,
  SHADOW_ENABLED,
  SHADOW_COLOR,
  SHADOW_X,
  SHADOW_Y,
  SHADOW_BLUR,
  OPACITY,
  VISIBLE,
  BORDER_RADIUS,
  FONT_FAMILY,
  FONT_SIZE,
  FONT_STYLE,
  TEXT,
  TEXT_DECORATION,
  TEXT_TRANSFORM,
  TEXT_ALIGN,
  TEXT_COLOR
}
