package zeus.shared.message.payload;

public enum NodeType {
  ROOT,
  MODEL_CHECKING_GATEWAY,
  MODEL_CHECKING,
  ABSTRACTION_GATEWAY,
  ABSTRACTION,
  COUNTEREXAMPLE_ANALYSIS_GATEWAY,
  COUNTEREXAMPLE_ANALYSIS
}
