export enum DesignerConfiguratorProperty {
  HEIGHT,
  WIDTH,
  POSITION_X,
  POSITION_Y,
  BORDER_RADIUS_TOP_LEFT,
  BORDER_RADIUS_TOP_RIGHT,
  BORDER_RADIUS_BOTTOM_LEFT,
  BORDER_RADIUS_BOTTOM_RIGHT,
  BORDER_WIDTH,
  BACKGROUND_COLOR,
  BORDER_COLOR,
  SHADOW_COLOR,
  SHADOW_X,
  SHADOW_Y,
  SHADOW_BLUR,
  OPACITY
}
