export enum Alignment {
  HORIZONTAL_LEFT = 'HORIZONTAL_LEFT',
  HORIZONTAL_RIGHT = 'HORIZONTAL_RIGHT',
  HORIZONTAL_CENTER = 'HORIZONTAL_CENTER',
  VERTICAL_TOP = 'VERTICAL_TOP',
  VERTICAL_CENTER = 'VERTICAL_CENTER',
  VERTICAL_BOTTOM = 'VERTICAL_BOTTOM'
}
